global:
  scrape_interval: 5s
  scrape_timeout: 5s

scrape_configs:
  - job_name: 'demo'
    enable_http2: false
    metrics_path: /metrics
    scrape_protocols:
    - PrometheusText0.0.4
    static_configs:
    - targets: ['api.demo.aspnet.kickstarter:8081']
