# To run from the command line, use the --build option to build the api image
# The command should be run from the folder containing this file
#
# docker compose -p demo-aspnet-kickstarter up -d --build
#
# API :     http://localhost:28080
# Grafana : http://localhost:28088/d/aspnetkickstarterdemo/aspnet-kickstarter-demo?orgId=1&refresh=5s

services:

  prometheus.demo.aspnet.kickstarter:
    image: prom/prometheus
    container_name: prometheus.demo.aspnet.kickstarter
    build:
      context: ./Prometheus
      dockerfile: Dockerfile
    restart: no
    ports:
      - 28082:9090 # HTTP

  grafana.demo.aspnet.kickstarter:
    image: grafana.demo.aspnet.kickstarter
    container_name: grafana.demo.aspnet.kickstarter
    build:
      context: ./Grafana
      dockerfile: Dockerfile
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=password
      - GF_AUTH_DISABLE_LOGIN_FORM=true
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Editor
    restart: no
    ports:
      - 28088:3000 # HTTP
    depends_on:
      - prometheus.demo.aspnet.kickstarter

  api.demo.aspnet.kickstarter:
    image: ${DOCKER_REGISTRY-}api.demo.aspnet.kickstarter
    container_name: api.demo.aspnet.kickstarter
    build:
      context: ../
      dockerfile: AspNet.KickStarter.Demo/Dockerfile
      target: final
    restart: no
    ports:
      - 28080:8080 # HTTP
      - 28081:8081 # Prometheus metrics
    depends_on:
      - grafana.demo.aspnet.kickstarter
