name: Build

on: [push]

jobs:
  build-and-test:

    runs-on: ubuntu-latest

    steps:

    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x

    - name: Build
      shell: pwsh
      run: dotnet build -c Release .\AspNet.KickStarter.sln

    - name: Test AspNet.KickStarter
      shell: pwsh
      run: |
        $workspace = $env:GITHUB_WORKSPACE
        dotnet test .\AspNet.KickStarter.Tests\AspNet.KickStarter.Tests.csproj -c Release --no-build --framework net8.0 -l "console;verbosity=normal" --results-directory:"$workspace/TestResults" /p:CollectCoverage=true /p:CoverletOutputFormat=opencover /p:CoverletOutput="$workspace/TestResults/ak.xml" /p:Include=[AspNet.KickStarter]* /p:Threshold=100

    - name: Test AspNet.KickStarter.CQRS
      shell: pwsh
      run: |
        $workspace = $env:GITHUB_WORKSPACE
        dotnet test .\AspNet.KickStarter.CQRS.Tests\AspNet.KickStarter.CQRS.Tests.csproj -c Release --no-build --framework net8.0 -l "console;verbosity=normal" --results-directory:"$workspace/TestResults" /p:CollectCoverage=true /p:CoverletOutputFormat=opencover /p:CoverletOutput="$workspace/TestResults/cqrs.xml" /p:Include=[AspNet.KickStarter.CQRS]* /p:Threshold=100

    - name: Report Generator
      uses: danielpalme/ReportGenerator-GitHub-Action@5.1.26
      with:
        reports: TestResults/ak.xml;TestResults/cqrs.xml
        targetdir: TestResults/CoverageReport
        reporttypes: TextSummary

    - name: Output Coverage Report
      shell: pwsh
      run:  |
        $workspace = $env:GITHUB_WORKSPACE
        $report = Get-Content "$workspace/TestResults/CoverageReport/Summary.txt" -Raw
        Write-Host $report
