name: Build

on: [push]

jobs:
  build-and-test:

    runs-on: windows-latest
    permissions:
      contents: read
      statuses: write

    steps:

    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x

    - name: Build
      run: dotnet build -c Release .\AspNet.KickStarter.sln

    - name: Test net8
      run: dotnet test .\AspNet.KickStarter.Tests\AspNet.KickStarter.Tests.csproj -c Release --framework net8.0 -l "console;verbosity=normal" -l "trx;logfilename=Net8TestResults.trx"
